---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: greeter
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: greeter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: greeter
spec:
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
      - name: greeter
        image: docker.io/markfisher/greeter:v1
        env:
        - name: GREETING
          value: Howdy

